core: add missing header for BSDs after 753c538dea87 (#630)
src/core/Seat.cpp:76:17: error: use of undeclared identifier 'close'
   76 |                 close(fd);
      |                 ^