pam: add missing header for libc++ after a4b056274963 (#589)
In file included from src/auth/Auth.cpp:2:
src/auth/Pam.hpp:43:5: error: no type named 'thread' in namespace 'std'; did you mean 'pthread'?
   43 |     std::thread           m_thread;
      |     ^~~~~~~~~~~
      |     pthread